name: Main Workflow

on: push

jobs:
  lint_and_test:
    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry shell

      - name: Pylint
        run: poetry run pylint underground test -d C0303,C0412,C0330,E1120,R0201,E0213,R0903,R0801

      - name: Pydocstyle
        run: poetry run pydocstyle underground test/*.py --verbose

      - name: Black
        run: poetry run black underground test --check --verbose

      - name: Pytest
        run: poetry run pytest . --cov=./ --cov-report=xml -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          name: ${{matrix.python-version}}
          file: ./coverage.xml

      - name: Build Publish to PyPi
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.python-version == 3.7
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --no-interaction --build -vvv -u __token__ -p $PYPI_TOKEN
